---
- name: Run Nginx container
  community.docker.docker_container:
    name: nginx
    image: nginx:latest
    ports:
      - "{{ nginx_port }}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    state: started
