- hosts: all
  become: yes
  gather_facts: yes

  vars:
    php_version: "8.2"
    php_enable_php_fpm: true
    php_fpm_pools:
      - name: www
        listen: "/run/php/php8.2-fpm.sock"
        user: "www-data"
        group: "www-data"
        pm: "dynamic"
        pm_max_children: 50
        pm_start_servers: 5
        pm_min_spare_servers: 5
        pm_max_spare_servers: 15

  pre_tasks:
    - name: Add PHP repository
      apt_repository:
        repo: "ppa:ondrej/php"
      when: ansible_distribution == 'Ubuntu'

  roles:
    - role: geerlingguy.php
    - nginx
    - postgresql
    - kafka
    - zookeeper