---
- name: Run Kafka container
  community.docker.docker_container:
    name: kafka
    image: bitnami/kafka:{{ kafka_version }}
    env:
      KAFKA_BROKER_ID: "1"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092"
    ports:
      - "9092:9092"
    state: started
